---
host: ":4001"
profiling: false
ssl:
  enabled: false
  host: ":433"
  key_file: "key.pem"
  cert_file: "cert.pem"
apps:
  - name: "App"
    enabled: true
    only_ssl: false
    key: "123abc"
    secret: "abc123"
    app_id: "1"
    user_events: true
    webhooks:
      enabled: true
      url: "http://127.0.0.1:5000/hook"